# Generated by Django 4.0.5 on 2023-07-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
    ]
