# Generated by Django 4.0.5 on 2023-07-29 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='person',
            name='gen',
            field=models.CharField(default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='person',
            name='hgt',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=5),
        ),
        migrations.AddField(
            model_name='person',
            name='phn',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='wgt',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='sky@gmail.com', max_length=254),
        ),
    ]
