# Generated by Django 4.0.5 on 2023-07-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0002_person_dob_person_gen_person_hgt_person_phn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='hgt',
        ),
        migrations.RemoveField(
            model_name='person',
            name='wgt',
        ),
    ]
