# Generated by Django 4.0.5 on 2023-07-29 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0002_remove_person_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
