# Generated by Django 4.0.5 on 2023-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='gen',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='phn',
            field=models.IntegerField(),
        ),
    ]
