# Generated by Django 4.0.5 on 2023-07-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gen', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
