# Generated by Django 4.0.5 on 2023-10-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
