# Generated by Django 4.0.5 on 2023-10-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_person_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.person')),
                ('degree', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
            ],
            bases=('hospital.person',),
        ),
    ]
