# Generated by Django 4.0.5 on 2023-11-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_date_doctorschedule_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='available_dates',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='timerange',
            name='doctor_schedule',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
        migrations.DeleteModel(
            name='TimeRange',
        ),
    ]
