# Generated by Django 4.0.5 on 2023-10-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='static/images/ai.jpg', upload_to=''),
        ),
    ]
