# Generated by Django 4.0.5 on 2023-10-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
