# Generated by Django 4.0.5 on 2023-10-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='keyword',
            field=models.CharField(default='eyes', max_length=100),
        ),
    ]
