# Generated by Django 4.0.5 on 2023-10-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_doctor_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='keyword',
            field=models.CharField(max_length=100),
        ),
    ]
