# Generated by Django 4.0.5 on 2023-11-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_appointment_scheduled_time_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
