# Generated by Django 4.0.5 on 2023-10-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_doctor_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.person')),
                ('address', models.CharField(default='Dhaka', max_length=200)),
            ],
            bases=('hospital.person',),
        ),
    ]
