# Generated by Django 4.0.5 on 2023-11-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_options_alter_patient_options'),
        ('hospital', '0011_remove_appointment_schedule_time_appointment_date_and_more'),
    ]

    operations = [
    ]
