# Generated by Django 4.0.5 on 2023-10-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
